Repository from-the-basement/elsm, pull requests merged in 2024-05, with the labels that each got.

#9 feat: impl `MemtableIterator`
  src/mem_table.rs
  src/oracle.rs
Labels: enhancement

#13 ci: add github action + issue/pr template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/ci.yml
Labels: documentation

#5 Feat/memtable freeze
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/mem_table.rs
  src/wal/mod.rs
Labels: enhancement

#15 Chore: use nightly toolchain on format check
  .github/workflows/ci.yml
Labels: invalid

#14 feat: `Db::get` can get data from Immutable
  src/index_batch.rs
  src/lib.rs
  src/mem_table.rs
  src/transaction.rs
  src/wal/mod.rs
Labels: enhancement

#12 Feat/recover from wal
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/serdes/mod.rs
  src/wal/mod.rs
  src/wal/provider/fs.rs
  src/wal/provider/in_mem.rs
  src/wal/provider/mod.rs
Labels: enhancement

#11 Feat/db&txn range
  Cargo.toml
  src/index_batch.rs
  src/index_batch/mod.rs
  src/index_batch/stream.rs
  src/lib.rs
  src/mem_table.rs
  src/mem_table/mod.rs
  src/mem_table/stream.rs
  src/oracle.rs
  src/stream/buf_stream.rs
  src/stream/merge_stream.rs
  src/stream/mod.rs
  src/transaction.rs
  src/utils.rs
Labels: enhancement

#17 Chore: remove Cargo.lock
  .gitignore
  Cargo.lock
Labels: invalid

#20 feat: add `Compactor` to listen CompactionTask
  Cargo.toml
  src/compactor/mod.rs
  src/index_batch/mod.rs
  src/index_batch/stream.rs
  src/lib.rs
  src/mem_table/mod.rs
  src/scope.rs
  src/stream/merge_stream.rs
  src/stream/mod.rs
  src/transaction.rs
  src/version/mod.rs
  src/wal/mod.rs
Labels: enhancement
